[package]
name = "radare3-mmap"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
memmap2.workspace = true
radare3-image.workspace = true

[lints.rust]
unsafe_code = "allow"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"
